Alegra command
platanus/alegra-integrations pull request #14
Opened 2018-02-02 15:55 UTC by camilo9020

2018-02-06 12:50 UTC, bunzli requested changes

2018-02-06 12:50 UTC, bunzli commented on app/models/document.rb
> +  def url_client
este nombre me confude.... tal vez algo como `bsale_customer_url`

2018-02-06 12:50 UTC, bunzli commented on app/clients/bsale_client.rb
> +  def get_client(url)
creo que debiera tener un nombre más genérico... porque no veo nada especial relacionado a un customer de bsale.

2018-02-06 12:50 UTC, bunzli commented on app/clients/alegra_client.rb
> +class AlegraClient
quedó confuso la existencia de un AlegraClient y un AlegraApiService.... debiéramos quedarnos con uno de los dos.

2018-02-06 12:50 UTC, bunzli commented on app/clients/alegra_client.rb
> +  def find_or_create_client(bsale_client)
la gracia de un client, es que no incluye lógica de negocio. Al recibir un bsale_customer, no se cumple esa regla.

2018-02-06 12:50 UTC, bunzli commented on app/clients/alegra_client.rb
> +  def alegra_client
el nombre `client` es muy desafortunado. Usemos customer mejor o contact... pero client confunde mucho

2018-02-06 19:26 UTC, bunzli requested changes

2018-02-06 19:26 UTC, bunzli commented on app/clients/alegra_client.rb
>        @document.update(alegra_status: :synced)
no se cayó esto?

2018-02-07 14:54 UTC, camilo9020 commented on app/clients/alegra_client.rb
>        @document.update(alegra_status: :synced)
No,  funcionó sin problemas

2018-02-08 11:35 UTC, bunzli approved these changes

2018-02-09 08:11 UTC, merged